# Generated by Django 5.0.4 on 2024-10-18 07:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_faq_answer_en_faq_answer_ru_faq_answer_uz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Answer'),
        ),
    ]
