# Generated by Django 5.0.4 on 2024-10-03 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_gallery_title_en_gallery_title_ru_gallery_title_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='rank',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High'), (3, 'Very high'), (4, 'Extreme'), (5, 'Critical')], default=5, verbose_name='Rank'),
        ),
        migrations.AddField(
            model_name='news',
            name='summary',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Summary'),
        ),
        migrations.AddField(
            model_name='news',
            name='summary_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Summary'),
        ),
        migrations.AddField(
            model_name='news',
            name='summary_ru',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Summary'),
        ),
        migrations.AddField(
            model_name='news',
            name='summary_uz',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Summary'),
        ),
        migrations.AddField(
            model_name='news',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Video URL'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='news/photos', verbose_name='Photo'),
        ),
        migrations.CreateModel(
            name='ViewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news', verbose_name='News')),
            ],
            options={
                'unique_together': {('news', 'ip_address')},
            },
        ),
    ]
