# Generated by Django 5.0.4 on 2024-10-03 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_rank_news_summary_news_summary_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewrecord',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_records', to='news.news', verbose_name='News'),
        ),
    ]
