# Generated by Django 5.0.4 on 2024-10-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_slug_newscategory_news_category_newsphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscategory',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Category title'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Category title'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Category title'),
        ),
    ]
