# Generated by Django 5.0.4 on 2024-10-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_newscategory_title_en_newscategory_title_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(null=True, upload_to='news/photos', verbose_name='Photo'),
        ),
    ]
