# Generated by Django 5.0.4 on 2024-10-17 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_news_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsphoto',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='news.news', verbose_name='News'),
        ),
    ]
