# Generated by Django 5.0.4 on 2024-10-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_newsphoto_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content2',
            field=models.TextField(blank=True, null=True, verbose_name='Second content'),
        ),
        migrations.AddField(
            model_name='news',
            name='content2_en',
            field=models.TextField(blank=True, null=True, verbose_name='Second content'),
        ),
        migrations.AddField(
            model_name='news',
            name='content2_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Second content'),
        ),
        migrations.AddField(
            model_name='news',
            name='content2_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Second content'),
        ),
    ]
