# Generated by Django 5.0.4 on 2024-10-18 06:20

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_newscategory_slug_alter_newscategory_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='content',
        ),
        migrations.RemoveField(
            model_name='news',
            name='content2',
        ),
        migrations.RemoveField(
            model_name='news',
            name='content2_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='content2_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='content2_uz',
        ),
        migrations.AlterField(
            model_name='news',
            name='content_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Content en'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Content ru'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_uz',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Content uz'),
        ),
    ]
