# Generated by Django 5.0.4 on 2024-10-18 06:26

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_remove_news_content_remove_news_content2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Content'),
        ),
    ]
