# Generated by Django 5.0.4 on 2024-10-18 06:27

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_news_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content2',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Second content'),
        ),
        migrations.AddField(
            model_name='news',
            name='content2_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Second content en'),
        ),
        migrations.AddField(
            model_name='news',
            name='content2_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Second content ru'),
        ),
        migrations.AddField(
            model_name='news',
            name='content2_uz',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Second content uz'),
        ),
    ]
