# Generated by Django 5.0.4 on 2024-10-18 06:39

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_news_content2_news_content2_en_news_content2_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content2_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Ikkinchi matn en'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content2_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Ikkinchi matn ru'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content2_uz',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Ikkinchi matn uz'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Matn en'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Matn ru'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_uz',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Matn uz'),
        ),
        migrations.AlterField(
            model_name='news',
            name='rank',
            field=models.IntegerField(choices=[(1, '⭐️'), (2, '⭐️⭐️'), (3, '⭐️⭐️⭐️'), (4, '⭐️⭐️⭐️⭐️'), (5, '⭐️⭐️⭐️⭐️⭐️')], default=5, verbose_name='Rank'),
        ),
    ]
