# Generated by Django 5.0.4 on 2024-10-18 06:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_alter_news_content2_en_alter_news_content2_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content2',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Second content'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content2_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Second content'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content2_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Second content'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content2_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Second content'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content'),
        ),
    ]
