# Generated by Django 5.0.4 on 2024-10-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcomment',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='comment/students', verbose_name='Photo'),
        ),
    ]
