# Generated by Django 5.0.4 on 2024-10-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edudirection',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Direction name'),
        ),
    ]
