# Generated by Django 5.0 on 2024-10-02 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edutype',
            name='description',
        ),
        migrations.AlterField(
            model_name='edutype',
            name='edu_type_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edu_types', to='education.edutypename'),
        ),
    ]
