# Generated by Django 5.0.4 on 2024-10-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_alter_edudirection_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduprogram',
            name='price',
            field=models.IntegerField(verbose_name='Contract price'),
        ),
        migrations.AlterField(
            model_name='edutype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Type name'),
        ),
    ]
