# Generated by Django 5.0.4 on 2024-10-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_alter_eduprogram_price_alter_edutype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='edudirection',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='edudirection',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='edudirection',
            name='content_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='edudirection',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Direction name'),
        ),
        migrations.AddField(
            model_name='edudirection',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Direction name'),
        ),
        migrations.AddField(
            model_name='edudirection',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Direction name'),
        ),
        migrations.AddField(
            model_name='edutype',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='edutype',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='edutype',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Type name'),
        ),
    ]
